# Generated by Django 5.1 on 2024-08-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
